### ISSUE TITLE
ref genome 

### ISSUE THREAD

**Issue by FAFUshiyan** [mquinodo/OFF-PEAK#2]
The error occurs because I am using the hs37d5.fa reference genome, which does not have "chr" in the chromosome names.

Feature (chrX:154976443-154996443) beyond the length of chrX size (0 bp).  Skipping.
Feature (chrX:155026269-155046269) beyond the length of chrX size (0 bp).  Skipping.
Feature (chrX:155076095-155096095) beyond the length of chrX size (0 bp).  Skipping.

**Comment by mquinodo** [comment]
Hello,
Thank you for reporting the issue. I will adapt the scripts so they work with such reference without "chr".
I guess in that case your BED file with the targeted regions also has no "chr"?
Best,
Mathieu

**Comment by FAFUshiyan** [comment]
Hello Mathieu,
Thank you for your response.
Yes, both my BED file and BAM files do not include "chr".


I have some additional questions I would like to ask:

  1.  In your article, you mentioned that a minimum of 15 control samples is required. Should these 15 control samples be included in the list_BAM.txt file along with the case samples?
  2.  When using the OFF-PEAK software, what specific processing steps are required for all BAM files?

Thank you for your help.

Best regards,


发件人: Mathieu Quinodoz ***@***.***>
日期: 星期一, 2024年4月15日 15:04
收件人: mquinodo/OFF-PEAK ***@***.***>
抄送: ShiYan ***@***.***>, Author ***@***.***>
主题: Re: [mquinodo/OFF-PEAK] ref genome (Issue #2)

Hello,
Thank you for reporting the issue. I will adapt the scripts so they work with such reference without "chr".
I guess in that case your BED file with the targeted regions also has no "chr"?
Best,
Mathieu

―

**Comment by mquinodo** [comment]
Hello,

I have added a --nochr option for the first script (01_targets-processing.sh) and adapted 02_coverage-count.sh. The output of the second script will add the "chr" and step 3 (03_OFF-PEAK.R) can be performed normally.

1. OFF-PEAK requires at least 15 samples to be run in a batch. When analyzing sample 1, it will take the 14 others as "controls". So you can simply put all the samples in the list_BAM.txt file (cases and controls or only cases).

2. I think I do not understand your question. Could you explain more?

Best,
Mathieu

**Comment by FAFUshiyan** [comment]
Hello Mathieu,

Thank you for the updates on the scripts and clarifying the process regarding the inclusion of control samples in the list_BAM.txt file.

Regarding the processing of BAM files, my question pertains to whether the following three steps are necessary:

  1.  samtools fixmate
  2.  GATK MarkDuplicates
  3.  GATK ApplyBQSR

I appreciate your assistance in clarifying this matter.

Best regards,
Yan

发件人: Mathieu Quinodoz ***@***.***>
日期: 星期二, 2024年4月16日 16:37
收件人: mquinodo/OFF-PEAK ***@***.***>
抄送: ShiYan ***@***.***>, Author ***@***.***>
主题: Re: [mquinodo/OFF-PEAK] ref genome (Issue #2)

Hello,

I have added a --nochr option for the first script (01_targets-processing.sh) and adapted 02_coverage-count.sh. The output of the second script will add the "chr" and step 3 (03_OFF-PEAK.R) can be performed normally.

  1.  OFF-PEAK requires at least 15 samples to be run in a batch. When analyzing sample 1, it will take the 14 others as "controls". So you can simply put all the samples in the list_BAM.txt file (cases and controls or only cases).
  2.  I think I do not understand your question. Could you explain more?

Best,
Mathieu

―

**Comment by mquinodo** [comment]
Hello,

These steps are not important as they will likely not influence the number of reads.

Best,
Mathieu
