### ISSUE TITLE
Unclear what the coverage value returned by 02_coverage-count.sh means

### ISSUE THREAD

**Issue by radinagg** [mquinodo/OFF-PEAK#4]
Hi there,

I am trying to quantify the percentage of on- and off-target reads in a bunch of BAM files from a targeted sequencing experiment performed using a small custom panel. To do this, I ran the first two steps of OFF-PEAK, but I am having some trouble interpreting the coverage value returned by `02_coverage-count.sh`. Can you explain if this corresponds to the number of bases within a given region that are covered by at least one read or, alternatively, the number of reads that map to that region (seems most likely based on the values)?

This is how I obtained the values:
```bash 02_coverage-count.sh --listBAM bam_files_list.txt --mosdepth mosdepth --work outputs --targetsBED data/twist-custom-panel.bed```

Thanks in advance,
Radina

**Comment by mquinodo** [comment]
Dear Radina,

Thank you for using OFF-PEAK.
OFF-PEAK is using mosdepth which is outputting the sum of per base coverage. So if your region has only one read of 150bp, the coverage will be 150. If you want the number of reads, then you need to divid by your read length.
I hope that answers your question.

Best regards,
Mathieu

**Comment by radinagg** [comment]
That's clear, thanks for the info!
