### ISSUE TITLE
Confusing descirption

### ISSUE THREAD

**Issue by tomlodz** [mquinodo/OFF-PEAK#5]
The description of point 3) CNV discovery is written unclearly.

In Required arguments, the descriptions are confused for me.

"-- output" does not refer to the bed file but to the folder where the results are to be placed

"-- data" is not the genome build but the data obtained during the coverage analysis, i.e. the ALL.target.tsv file

**Comment by mquinodo** [comment]
Thank you for reporting.
It has been now corrected.
